
package language.parser.nodes;

import language.parser.Visitor;


/**
 * This class was generated by the LRPaGe parser generator v1.0 using the com.sun.codemodel library.
 * 
 * <P>LRPaGe is available from https://github.com/tbepler/LRPaGe.
 * <P>CodeModel is available from https://codemodel.java.net/.
 * 
 */
public class Conditional
    extends expAbstractNode
{

    public final expAbstractNode exp0;
    public final expAbstractNode exp1;
    public final expAbstractNode exp2;

    public Conditional(_Punctuation9Token _punctuation90, expAbstractNode exp1, _Punctuation10Token _punctuation102, expAbstractNode exp3, _Punctuation11Token _punctuation114, expAbstractNode exp5) {
        this.exp0 = exp1;
        this.exp1 = exp3;
        this.exp2 = exp5;
    }

    @Override
    public int getLine() {
        return exp0 .getLine();
    }

    @Override
    public int getPos() {
        return exp0 .getPos();
    }

    @Override
    public void accept(Visitor visitor) {
        visitor.visit(this);
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = ((hash* 13)+ exp0 .hashCode());
        hash = ((hash* 13)+ exp1 .hashCode());
        hash = ((hash* 13)+ exp2 .hashCode());
        hash = ((hash* 13)+ getClass().hashCode());
        return hash;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (null == o) {
            return false;
        }
        if (!(o instanceof Conditional)) {
            return false;
        }
        Conditional castResult = ((Conditional) o);
        if (!this.exp0 .equals(castResult.exp0)) {
            return false;
        }
        if (!this.exp1 .equals(castResult.exp1)) {
            return false;
        }
        if (!this.exp2 .equals(castResult.exp2)) {
            return false;
        }
        return true;
    }

}
