
package language.parser.nodes;

import language.parser.Visitor;


/**
 * This class was generated by the LRPaGe parser generator v1.0 using the com.sun.codemodel library.
 * 
 * <P>LRPaGe is available from https://github.com/tbepler/LRPaGe.
 * <P>CodeModel is available from https://codemodel.java.net/.
 * 
 */
public class Where
    extends expAbstractNode
{

    public final expAbstractNode exp0;
    public final assign_Punctuation14ListAbstractNode assign_punctuation14list1;

    public Where(expAbstractNode exp0, _Punctuation12Token _punctuation121, _Punctuation13Token _punctuation132, assign_Punctuation14ListAbstractNode assign_punctuation14list3, _Punctuation15Token _punctuation154) {
        this.exp0 = exp0;
        this.assign_punctuation14list1 = assign_punctuation14list3;
    }

    @Override
    public int getLine() {
        return exp0 .getLine();
    }

    @Override
    public int getPos() {
        return exp0 .getPos();
    }

    @Override
    public void accept(Visitor visitor) {
        visitor.visit(this);
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = ((hash* 13)+ exp0 .hashCode());
        hash = ((hash* 13)+ assign_punctuation14list1 .hashCode());
        hash = ((hash* 13)+ getClass().hashCode());
        return hash;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (null == o) {
            return false;
        }
        if (!(o instanceof Where)) {
            return false;
        }
        Where castResult = ((Where) o);
        if (!this.exp0 .equals(castResult.exp0)) {
            return false;
        }
        if (!this.assign_punctuation14list1 .equals(castResult.assign_punctuation14list1)) {
            return false;
        }
        return true;
    }

}
